" zebult vimrc

" deoplete must setting
let g:python3_host_prog = expand('~/.pyenv/shims/python3')
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/deoplete.nvim

if &compatible
  set nocompatible
endif

" rc読み込み TODO: 関数の内容理解する
function! s:source_rc(path, ...) abort "{{{
  let use_global = get(a:000, 0, !has('vim_starting'))
  let abspath = resolve(expand('~/.vim/rc/' . a:path))
  if !use_global
    execute 'source' fnameescape(abspath)
    return
  endif

  " substitute all 'set' to 'setglobal'
  let content = map(readfile(abspath),
        \ 'substitute(v:val, "^\\W*\\zsset\\ze\\W", "setglobal", "")')
  " create tempfile and source the tempfile
  let tempfile = tempname()
  try
    call writefile(content, tempfile)
    execute printf('source %s', fnameescape(tempfile))
  finally
    if filereadable(tempfile)
      call delete(tempfile)
    endif
  endtry
endfunction"}}}

if has('vim_starting')
  call s:source_rc('init.rc.vim')
endif

call s:source_rc('filetype.rc.vim')
call s:source_rc('path.rc.vim')
call s:source_rc('dein.rc.vim')
call s:source_rc('mappings.rc.vim')
" call s:source_rc('view-tomorrow-night.rc.vim')
call s:source_rc('view-nefertiti.rc.vim')
call s:source_rc('skeleton.rc.vim')
call s:source_rc('dict.rc.vim')
call s:source_rc('script.rc.vim')
call s:source_rc('macro.rc.vim')
call s:source_rc('util.rc.vim')

" original function
source ~/Dropbox/Saichi/Vim/Macros/sedItem.vim
source ~/Dropbox/Saichi/Vim/Macros/cleanSpace.vim

let g:metarw_alias = {
  \ 'myhome' : '~',
  \ }

autocmd BufNewFile *.cs norm! 3j2wi%3dh 
autocmd BufNewFile *.md norm! i# %"zx"zx"zxo
autocmd BufNewFile *.java norm! 2wi%5dh 
autocmd BufNewFile *.h norm! i% bbb:%s/CLASS_NAME//gggveeelx
autocmd BufNewFile *.hpp norm! i% bbb:%s/CLASS_NAME//gggveeelx

" このタイミングで呼ばないと補完が選択状態で開始されない
call s:source_rc('plugins/deoplete.rc.vim')

""""""""""""""""""""""""""""""
" grepをQuickFixで開く
""""""""""""""""""""""""""""""
augroup grepopen
    " autocmd!
    " autocmd QuickfixCmdPost vimprep cw
    autocmd QuickFixCmdPost *grep* cwindow
augroup END
"""""""""""""""""""""""""""""
