" zebult vimrc

" deoplete must setting
let g:python3_host_prog = expand('~/.pyenv/shims/python3')
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/deoplete.nvim

if &compatible
  set nocompatible
endif

" rc読み込み TODO: 関数の内容理解する
function! s:source_rc(path, ...) abort "{{{
  let use_global = get(a:000, 0, !has('vim_starting'))
  let abspath = resolve(expand('~/.vim/rc/' . a:path))
  if !use_global
    execute 'source' fnameescape(abspath)
    return
  endif

  " substitute all 'set' to 'setglobal'
  let content = map(readfile(abspath),
        \ 'substitute(v:val, "^\\W*\\zsset\\ze\\W", "setglobal", "")')
  " create tempfile and source the tempfile
  let tempfile = tempname()
  try
    call writefile(content, tempfile)
    execute printf('source %s', fnameescape(tempfile))
  finally
    if filereadable(tempfile)
      call delete(tempfile)
    endif
  endtry
endfunction"}}}

if has('vim_starting')
  call s:source_rc('init.rc.vim')
endif

call s:source_rc('filetype.rc.vim')
call s:source_rc('dein.rc.vim')
call s:source_rc('mappings.rc.vim')
call s:source_rc('view.rc.vim')
call s:source_rc('skeleton.rc.vim')
call s:source_rc('dict.rc.vim')
call s:source_rc('script.rc.vim')
autocmd BufNewFile *.cs norm! 3j2wi%3dh 
autocmd BufNewFile *.md norm! i# %xxxo
autocmd BufNewFile *.java norm! 2wi%5dh 

" tomlから呼べない為ここで呼ぶ
call s:source_rc('plugins/deoplete.rc.vim')
" call s:source_rc('plugins/neocomplete.rc.vim')
call s:source_rc('plugins/denite.rc.vim')
call s:source_rc('plugins/fugitive.rc.vim')
call s:source_rc('plugins/quickrun.rc.vim')
call s:source_rc('plugins/gtags.rc.vim')
call s:source_rc('plugins/submode.rc.vim')
call s:source_rc('plugins/smartchr.rc.vim')

""""""""""""""""""""""""""""""
" grepをQuickFixで開く
""""""""""""""""""""""""""""""
augroup grepopen
    " autocmd!
    " autocmd QuickfixCmdPost vimprep cw
    autocmd QuickFixCmdPost *grep* cwindow
augroup END
"""""""""""""""""""""""""""""
