#!/bin/sh

cd /0CheatSheet
git add .
git commit -m "data update: "`date +%Y_%m_%d_%H`
git push origin master


cd ~/dotfiles
# .vimrcを他ファイルに適応
\cp -f .vimrc .xvimrc
sed -i -e 's/noremap\ j\ gj/\"noremap\ j\ gj/g' .xvimrc
sed -i -e 's/noremap\ k\ gk/\"noremap\ k\ gk/g' .xvimrc
sed -i -e 's/noremap\ gj\ j/noremap\ gj\ i\<Down\>\<Esc\>\<Right\>/g' .xvimrc
sed -i -e 's/noremap\ gk\ k/noremap\ gk\ i\<Up\>\<Esc\>\<Right\>/g' .xvimrc
sed -i -e 's/Leader/Space/' .xvimrc
rm -f .xvimrc-e

git add .
git commit -m "data update: "`date +%Y_%m_%d_%H`
git push origin master
