#!/bin/sh
# dotfileをアップデートするシェル

cd dotfiles

# .vimrcを他ファイルに適応
\cp .vimrc .xvimrc
sed -i -e 's/noremap\ j\ gj/"\ noremap\ j\ gj/g' .xvimrc
sed -i -e 's/noremap\ k\ gk/"\ noremap\ k\ gk/g' .xvimrc
rm -f .xvimrc-e
# \cp .vimrc .vrapperrc
# sed -i -e 's/noremap\ j\ gj/"\ noremap\ j\ gj/g' .vrapperrc
# sed -i -e 's/noremap\ k\ gk/"\ noremap\ k\ gk/g' .vrapperrc
# rm -f .vrapperrc-e

# gitにpush
git add .
git commit -m "dotfiles update"
git push origin master
