" GUIツールバーを非表示
set guioptions-=T
" 複数存在すれば表示
set showtabline=1
set guioptions-=e
" メニューバーなし
set guioptions-=m
" 右スクロールバーなし
set guioptions-=r
set guioptions-=R
" 左スクロールバーなし
set guioptions-=l
set guioptions-=L
" 下スクロールバーなし
set guioptions-=b
" mac os x環境固有の設定
if has('mac')
   set guifont=Ricty\ Regular:h12
   " フォーカス時以外透明度上げる
   " autocmd FocusGained * set transparency=8
   " autocmd FocusLost * set transparency=20
   autocmd FocusGained * set transparency=0
   " 暗い背景色用の配色を使う?
   set background=dark
endif
let g:did_install_default_menus = 1
let g:did_menu_trans = 1
set guioptions-=m

" macvim python3 enable
let $PYTHON3_DLL="/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/Python"

