" タブを表示
set showtabline=2
" GUIツールバーを非表示
set guioptions-=T
" 複数存在すれば表示
set showtabline=1
" メニューバーなし
set guioptions-=m
" 右スクロールバーなし
set guioptions-=r
set guioptions-=R
" 左スクロールバーなし
set guioptions-=l
" 下スクロールバーなし
set guioptions-=b
let g:neocomplete#lock_iminsert = 1
" mac os x環境固有の設定
if has('mac')
   " フォントサイズを15ポイントに設定
   " set guifont=Ricty-RegularForPowerline:h16
   set guifont=Ricty\ Regular:h16
   " フォーカス時以外透明度上げる
   autocmd FocusGained * set transparency=5
   autocmd FocusLost * set transparency=10
   " 暗い背景色用の配色を使う?
   set background=dark
endif
let g:did_install_default_menus = 1
let g:did_menu_trans = 1
set guioptions-=m
