let g:plugin_mode = 0
if len(findfile(".development.vim", ".;")) > 0
  let g:plugin_mode = 1
  set runtimepath&

  execute 'set runtimepath+=' . getcwd()

  for plug in split(glob(getcwd() . "/*"), '\n')
    execute 'set runtimepath+=' . plug
  endfor
endif

" execute 'source' fnamemodify(expand('<sfile>'), ':h').'/rc/simple.rc.vim'
execute 'source' fnamemodify(expand('<sfile>'), ':h').'/rc/vimrc'

" let g:python3_host_prog = expand('~/.pyenv/shims/python3')
"
" if &compatible
"   set nocompatible
" endif
" set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim
"
" call dein#begin(expand('~/.cache/dein'))
"
" call dein#add('Shougo/dein.vim')
" call dein#add('Shougo/deoplete.nvim')
" call dein#add('zchee/deoplete-clang')
" call dein#add('haya14busa/vim-edgemotion')
"
" call dein#end()
" call dein#save_state()
"
" map <C-j> <Plug>(edgemotion-j)
" map <C-k> <Plug>(edgemotion-k)
"
" setlocal omnifunc=syntaxcomplete#Complete
"
" let g:deoplete#enable_at_startup = 1
" " let g:deoplete#auto_complete_delay = 0
" " set completeopt+=noinsert
"
" let g:deoplete#sources#clang#libclang_path = '/Library/Developer/CommandLineTools/usr/lib/libclang.dylib'
" let g:deoplete#sources#clang#clang_header  = '/Library/Developer/CommandLineTools/usr/lib/clang'
" " let g:deoplete#sources#clang#clang_header  = '/Library/Developer/CommandLineTools/usr/lib/clang/7.3.0/include/'
" " let g:deoplete#sources#clang#std#cpp = 'c++11'
