call altr#define('%.vsh', '%.fsh')
call altr#define('%.vert', '%.frag')
" call altr#define('*Model.cs', '*View.cs', '*Presenter.cs')
call altr#define('dein.toml', 'dein_lazy.toml')
call altr#define('autoload/%.vim', 'doc/%.txt', 'plugin/%.vim')
