call altr#define('%.vsh', '%.fsh')
call altr#define('%.vert', '%.frag')
call altr#define('dein.toml', 'dein_lazy.toml')
call altr#define('autoload/%.vim', 'doc/%.txt', 'plugin/%.vim')
call altr#define_contain('Model','View','Presenter')
call altr#define_contain('Common','Base')
